name: Deployment
# set trigger actions to active
on:
  push:
    branches:
      - main
# what doing job execute when actions
jobs:
  build-docker:
    name: build and push to docker registry
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          docker build -t msidik17/mini-project:latest \
            --build-arg DB_USER=${DB_USER} \
            --build-arg DB_PASS=${DB_PASS} \
            --build-arg DB_HOST=${DB_HOST} \
            --build-arg DB_PORT=${DB_PORT} \
            --build-arg DB_NAME=${DB_NAME} \
            --build-arg JWT_SECRET=${JWT_SECRET} \
            .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker
        run: docker push msidik17/mini-project:latest
  deploy:
    name: deployment to server
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            whoami

            docker pull msidik17/mini-project:latest
            docker stop go-mini-project-app || true
            docker rm go-mini-project-app || true

            docker run -d -p 8000:8000 --name go-ci-cd-app \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              msidik17/mini-project:latest